site_name: Python-server
site_url: https://Python-server.nry2025.xyz
theme:
  name: material
  language: en
  icon:
    repo: fontawesome/brands/github
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - content.code.copy

extra:
  generator: false
  social:
    - icon:  fontawesome/brands/github
      link: https://github.com/fuydg

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

copyright: Copyright &copy; 2025 fuydg build is fueled by 💙 and hot drinks

repo_url: https://github.com/fuydg/Python-server
repo_name: Python-server
